---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pagos-service-secrets
  namespace: sa-p8
spec:
  encryptedData:
    DATABASE_URL: AgA7ZgDdf2CeM2vyVa9VfTobp8ENtKKHyKAafMbI3p/AGA0ohjbUjTJsmay4xN+f76aMyXc217rsQZoJxWxMarMHuUrtoolFVcsbCdCu9lZB9h+ZlGFD8Ek3oiVRC64N76SeFao7duWfOHp+/1B3PYQB2Xj/BB4RSnitIcinlVZeKUs6we0JvACEC9ZsHirgmvsQYg52LakSaL2SKJDoXX9XJMCpMbNw9T2KVtnakYj0DJg63JSBmhp9UElVefZ87PAD8dWTUGVutoLtUS9qmmWXwVY3osSsI/u6sEcr6RgosylZg0FJLyPsizLk3oBgTescOX97a9ytW/op4pDD2ij5uleNDE3WZ+EbJkz4X2297DgUuS4Qt4Hs7o7GhXSx4KNMy08XX0La+w7O2rJE/b4SdXLIfuVKDNCaB/Q6Kb9DmRY0ZUIUvcKAChFSXXq6a3HN4S9ljT7FA6mFfJw4zIybdvf+SztWT/WdqJYiXLmoUvEg5xY5jAxhLYNsw7C4qSmCvxSeZjbuohwAVMMqBkSC3XnD/YqnuUEcHkCscSIyOi00inCwD4Ln6Gmp3dktgXs2joOdd0JXc3aPbGpoH3dL4QdF5fooaK99tS0Dk6ZuHE1EN7ilG0qjtxn1YdmLnXtMf8wujAbbB0rgIQL5JaeJwmOmMhrUDztYV46vqLX7/BmH0iZbszmrO5ZcFLDr2CMNkq8cs69dCidQRz+0yq5k8or2pVxHXjK9aBwzNs1Vp4bW5/QHbBiUjWqVV3kZH4Ieez3TcJTGNDg/LQ6rzcT6SHN88L5E4gkYwRNRQSnaS6JD9V6HvD2o2lwpOzd5MOWpESSzOrqc+dwvSpM5J4tBKzz7BC2h79kosPV3wnJMT67tZYb9B0n3kmAReXZk
  template:
    metadata:
      name: pagos-service-secrets
      namespace: sa-p8
