---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ordenes-service-secrets
  namespace: sa-p8
spec:
  encryptedData:
    DATABASE_URL: AgCBOMhjBek0AUil1WA6NHmQbXWC4XSQyoRHfrHceDeaiYicn5D8bflmALizRzVUwoxtQhq/HJ3+PBsqhRLKUJYAgNFLm9gnboqacrrEIVYb77RQA5TzSn25BFUPdtIPxQVKXbvdvLSlM8M/EJmrgKTMDewYUJnSQO4c/t+gCP8F7+g3glDaDHnET8NKdGf1rLAvhmq32J7TROOAGOLo5dHzE0wuHiFKMyEax42kywp92NgWXnjPjMjdJi20lZcdJlkSdPuGd7Z7dCe6zjhV89IWmwUyd3Ym6NtqvwE9fn+BzrDNMEgBrJxf5EuMMPmIF229TnQkxbxZUIK0smGaqvY9V7/cbHhO4ogAuuc8lIdiiiecvtYUURg3CaQOg1dQ53FH2jgKVCAW0Y4MTq0Qm+jztMJlmNgJOGVPLqGZyuW1WdT3h3HQINs9FxtWJEP2UEZvR4064/ekAFnA53qaiphO2SFgISMZLVOgQOPvKqHE3fbwXv+LvANuJQGWVys1+lzrud8ObEOJpGaUXrbKXujROiZ5mvCGGSdfKY5Etxr1+8PFaAEoPsjWKY+XD9wod7WTu44wBaNwVB5XmoC2R9Iv8QwiCDe1/SNT3OwM6AJavuHsIb9CBVvSfofF7pA6hClK20JW3Yy8Y/lxbQtroLOZ21H1tDWfwQUDh7f45cYNZRAguixXX8CtV/fnTWQkIXvgQ6RM1OQ9yXGs/pSRvMho84sDaNmNnc2wwOCO5LM6ZeQ/FYR1w3mDBxfX6WHxbcI9OFsyjkBhOlMrso6mdpL5Z18RX4MBXhMdnsP/PPrj4JND34uk6L81kmzJb7JS0fAJC9s11A9R22sZjiN4htOMYoj2Su1tg3x1XOdW7jpFfyt5B30ykkU6wxuMAJzn+QI=
  template:
    metadata:
      name: ordenes-service-secrets
      namespace: sa-p8
