---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-productos-credentials
  namespace: sa-p8
spec:
  encryptedData:
    password: AgCiI1PED7b70uKrh0LIwAV6f53b38r5r4CKHRdEUIrwuHUZF+g8Xi2I7jRCvw7qABIiiBs2xQkpEsfXyg9LY05K7xqlupgKN9C2KWdwe4smrZDBwGu0LomhY/Nv6k5/oZpFPEPyqJCp06YK7UAvE/zwqOTnQptbAA4FzFUlIuKjnj7BUAgsMAwekjlUbRgi3WyzBG4/ZndGvaRiypch902v/w8BP7XtZWrMjDfZ0O5Bhf1te7YNNljqmvIHYezYgCcUT4rzQsBKHoX3AZ1zWAD6zRCf9HQiILtr4kh6ZeIymfacfXLNoNusYbmuAthrJyyvN2n2vVTI3LjQf8NeLITfI7QPiUFKZHL9ZuL8jtdFrMOtwpvc1GW80smkB26Os8D+D9o1fjMO81mRCMQdzvM/Giv7oIqHcJp3TKlVvhTWDfp9qUo69jQBP+tbStjkHI8HPVEkeZPEDpQEM6+Ti/Fbht/5O3jnO0H2soszM71L/VfWC8W5bksDrmulHihWJCN13LWypIsaQvj7XIEXJeUXHNJyOFGBIZ9nelE01aHOW4z03Nieu4K6tkHKoxyY4LOyzM35LkK/CN2V2Ocr/PqwobKlLTj+ehPsBM4ZUUKse+/8qnfWI0u5ZytHSSm7Db6umzchCzSFukFvQDr5ecsZcImHqwtKgwZSJxAm/22XLLzUfyVgYnGHKJ7q60f88R4kpeS6sSNdP5MuJDdd8xneJ9zdUW9NHwWpEtctketZNQ==
  template:
    metadata:
      name: postgres-productos-credentials
      namespace: sa-p8
