---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: productos-service-secrets
  namespace: sa-p8
spec:
  encryptedData:
    DATABASE_URL: AgDPZ3Pku1Dsdy+rjKabpNnNssDu6D8o0gaAteI4uiV+Py3QXmgMNZYIpb2mCkXAUpEnlNAHHSiqcUCo75VZuXj1ISA+cViJTQE4o2uJO4n20s/54MhGxqvBB4dDom2zyAmgygu1M0C+dIs9D6pbt3xnKNs5avitvW8dzeToVAtpGc82fRK2S81TfQWIeYgfLYYfbh5vBJ8n1FfaCeWoT8C/IvH8mAVjkJ28+fNkalv8CYWdng8X6AHP8RzZWu8TKBek+f+WU4W8x5qpaK4YW+p1NR75GcNZnPvoU7/gtANv5Dzq84UR45rhScf0X7t4zrj7J+w1ROGKgx1+z/yOJAxVPoOY4L1tI/WiI2b9VHbD8BnhckSHMcCohbJy1txg2f5qRFPdNKLJCJawnuqi1EdglIdvUEzgAf2EMI4cnVCuVDdG2tPPIYCw3PhuAuJxoWn86aBmu2frxFp3GVpynLul6punMRQJ1lrWSPjrKO24HzD9oUt+A/FE3y0crH3oNUFi0uqkSmDyHoS/E9vTGlOLZ1FU1K2gVEa7/vnqEed4VFQnxcp7pJVeBkbs/NbhuocBTA/DzToJi0mc291LYgY2Ru8Dk/zaM2LXAuCn+3gfVpwGTkd74drSfupONSM/elqBSSU2jf7XCULnLTrTMTV200PKYa9KjAEIO+76CA+OAQt4wCrnI+6V5/fnOzLhQt9EsvAYnoRIANbJAMUTWpK8hGKwGwoEK9OVdBSyq818sMfl35oQW5nkEyRDQCCoV1gSvUMdEsL77Wr+FVTPVChfwEQ3u508yqnxCOTTNfTavm3x7G0EAAljkj61ddQrkrQNLpIPB6hw3tn9gkHY8HWobg==
  template:
    metadata:
      name: productos-service-secrets
      namespace: sa-p8
