---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: sa-p8
spec:
  encryptedData:
    .dockerconfigjson: AgDZHX1Veerie5fS+RoEYQc6OeQXazzPtgDjZScaYp5/EV1LGNG992EP/9ET0SPD3JQJIh3bqxihuqskqIUPKQJC9dOAuLQcURjeZPBPdaH5k60bszafWcwML+YFVhjfXYK1Y+o++gAslI0b1JifZTtimiouopfgG1etp4YTowZPO9RTXNxXqX3HVSoWxA5X8c2TxBBdFyuTWGpweyUZypLd3Cb42o8mYpUoiVC0UCqd4zbWH4SXF55mbni4L6jmEuLKLsMVzxT/Uco+gVFp/CsZV9xO4qZvJLvSX12wY8RLFskj9f5wRHecPY3DutJv6cke3MQDLZuwdaweDT1lyUcT/3k7cyh7nzlQwlqyZSHmMEpjv8liQzfLBxOmVAUCiunwt8f1xeB98IOya/tmXU1HA7Jt5gYoMSmKitbtqGKtALLFRxIktkBAeGRD0p5kvyxoJjLc3rFI0j2llI1c+nBVwWtYlcwfFSiXPUKdQvXSbUUO3K3nJLl2QkUfBOkg/20Ixv6Zv17ABUZJvGDn+ScdWW/W1TZZjKzVUzSRIH3vxJqYjammxiAX3EaiiuZLFiHHcFrArKltSrjWgxewL+/WkyDjxj8PYqn7jze7oBYORplYEOtw8jVBFy9MSFsxv2EKzoF/evRlqq/P6wnHPi8HvHSuL2YsLrffdIU7ZYOoLzsIeFlx8l6jMEcRtgmPe7i7PUxJeiUzA0f2SoibCOM7BcbrRedZ0vcoIE6EfBLNQJ7szPn/yTO00R+C29qFG+1xU4rYpxuTcVUgudrySTAC/qBwnCQ4O/krzOvmj+AFGLFxBjCTL5IpX2t9o/j7GVrUHPjWSquT8kLjiGUUvhd3t5hhOqZvH4RiL3Rly/o33FR2W5VPuqazVQ91rJRfOIGx8jiBBTBynT9hqZn6XCTFl4g/77GaZbBA1wilivJFRczl
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: sa-p8
    type: kubernetes.io/dockerconfigjson
